# Generated by Django 3.1.5 on 2021-01-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='saleman',
            options={'verbose_name': 'Продавец'},
        ),
        migrations.AlterModelOptions(
            name='tagproduct',
            options={'verbose_name': 'Тэги '},
        ),
        migrations.AlterField(
            model_name='product',
            name='saleman_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleman_product', to='main.saleman'),
        ),
    ]
