# Generated by Django 3.1.5 on 2021-01-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210123_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleman',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
