# Generated by Django 3.1.5 on 2021-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210125_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'saleman',
            name = 'article',
            field = models.CharField(max_length=10,blank=True)
        )


    ]
