# Generated by Django 3.1.5 on 2021-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210125_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleman',
            name='article',
            field=models.CharField(max_length=20, default='default-article')
        )
    ]
