# Generated by Django 3.1.5 on 2021-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210211_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_product',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата добавления товара'),
        ),
    ]
