# Generated by Django 3.1.5 on 2021-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='counter',
            field=models.IntegerField(),
        ),
    ]
