# Generated by Django 3.1.5 on 2021-02-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_product_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
